# Generated by Django 5.1.1 on 2024-10-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_email_remove_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
