# Generated by Django 5.1.1 on 2024-10-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_diary_sentiment_user_nickname_delete_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
